$background = f6fafb
$onBackground = 2a3436
$surface = f6fafb
$surfaceDim = d1dcde
$surfaceBright = f6fafb
$surfaceContainerLowest = ffffff
$surfaceContainerLow = eff5f6
$surfaceContainer = e8eff1
$surfaceContainerHigh = e1eaec
$surfaceContainerHighest = dae4e7
$onSurface = 2a3436
$surfaceVariant = dae4e7
$onSurfaceVariant = 576163
$outline = 727c7f
$outlineVariant = a9b4b6
$inverseSurface = 0a0f10
$inverseOnSurface = 999e9f
$shadow = 000000
$scrim = 000000
$surfaceTint = 1d6874
$primary = 1d6874
$primaryDim = 065c68
$onPrimary = edfcff
$primaryContainer = a4e8f6
$onPrimaryContainer = 005762
$inversePrimary = a4e8f6
$primaryFixed = a4e8f6
$primaryFixedDim = 96d9e7
$onPrimaryFixed = 00424c
$onPrimaryFixedVariant = 11616d
$secondary = 4b6368
$secondaryDim = 3f575c
$onSecondary = edfcff
$secondaryContainer = cde7ed
$onSecondaryContainer = 3e565b
$secondaryFixed = cde7ed
$secondaryFixedDim = bfd9df
$onSecondaryFixed = 2b4348
$onSecondaryFixedVariant = 485f65
$tertiary = 446182
$tertiaryDim = 375575
$onTertiary = f7f9ff
$tertiaryContainer = b9d7fd
$onTertiaryContainer = 2d4b6a
$tertiaryFixed = b9d7fd
$tertiaryFixedDim = abc9ee
$onTertiaryFixed = 183856
$onTertiaryFixedVariant = 375574
$error = a83836
$errorDim = 67040d
$onError = fff7f6
$errorContainer = fa746f
$onErrorContainer = 6e0a12
$primaryPaletteKeyColor = 3b808d
$secondaryPaletteKeyColor = 637b80
$tertiaryPaletteKeyColor = 5c799b
$neutralPaletteKeyColor = 737879
$neutralVariantPaletteKeyColor = 6f797b
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 3b808d
$secondary_paletteKeyColor = 637b80
$tertiary_paletteKeyColor = 5c799b
$neutral_paletteKeyColor = 737879
$neutral_variant_paletteKeyColor = 6f797b
$term0 = 9a9b9a
$term1 = 005bcc
$term2 = 008f8f
$term3 = 427d3b
$term4 = 00998f
$term5 = 0071a3
$term6 = 168d9d
$term7 = 1f2224
$term8 = 0f0f0f
$term9 = 0071fa
$term10 = 00b2b3
$term11 = 5d9954
$term12 = 41bdb2
$term13 = 008cca
$term14 = 48aebf
$term15 = 26292b
$rosewater = 7d76b1
$flamingo = 6470bd
$pink = 0085c0
$mauve = 005b79
$red = 003ee0
$maroon = 2751f9
$peach = 198900
$yellow = 008f68
$green = 007c7d
$teal = 007381
$sky = 00859d
$sapphire = 007e8f
$blue = 00627a
$lavender = 007c9b
$klink = 0094af
$klinkSelection = 0094af
$kvisited = 008ab9
$kvisitedSelection = 008ab9
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bcc1
$kpositiveSelection = 00bcc1
$text = 2a3436
$subtext1 = 576163
$subtext0 = 727c7f
$overlay2 = 828b8e
$overlay1 = 949c9f
$overlay0 = a5adaf
$surface2 = b8bec0
$surface1 = cbd1d2
$surface0 = e0e5e7
$base = f6fafb
$mantle = eef1f2
$crust = e9ecec
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
